# T-test_one_sample_test

In [51]:
# statment: comparing the sample mean is equal to population mean 

In [40]:
age=np.linspace(1,100,32).round(0)

In [52]:
age # population 

array([  1.,   4.,   7.,  11.,  14.,  17.,  20.,  23.,  27.,  30.,  33.,
        36.,  39.,  43.,  46.,  49.,  52.,  55.,  58.,  62.,  65.,  68.,
        71.,  74.,  78.,  81.,  84.,  87.,  90.,  94.,  97., 100.])

In [42]:
import numpy as np

In [43]:
age_mean=np.mean(age)
print(age_mean)

50.5


In [45]:
#let sample
sample_size=10
age_sample=np.random.choice(age,sample_size)

In [46]:
age_sample

array([39., 11., 46., 23., 46., 87., 90.,  7., 90., 97.])

In [47]:
from scipy.stats import ttest_1samp

In [ ]:
# Null hypo; no differene the sample mean & population mean
# Alternate hypo: there is significant different 

In [48]:
ttest,pvalue=ttest_1samp(age_sample,age_mean)

In [49]:
pvalue
## hypothessis condition 
# pvalue is less than than 0.5 -- reject the null hypo
# pvalue more than 0.5-- failed to reject null hypo

0.7845556637097182

In [50]:
if pvalue<0.05:
    print('reject the null hypo')
else:
    print('failed to reject the null hypo')

failed to reject the null hypo


# consider the age in a school & in one class

In [53]:
import scipy.stats as stats

In [64]:
np.random.seed(10)
school_age=stats.poisson.rvs(loc=18,mu=35,size=1500)
class_age=stats.poisson.rvs(loc=18,mu=30,size=60)

In [65]:
class_age.mean()

48.3

In [67]:
_,p_value=stats.ttest_1samp(class_age,school_age.mean())

In [68]:
school_age.mean()

52.75333333333333

In [69]:
p_value

5.2743973761006257e-08

In [70]:
if p_value<0.05:
    print('reject the null hypo')
else:
    print('failed to reject the null hypo')

reject the null hypo


## Two_sample T-test

In [71]:
# compare mean of two independent groups to determine there is statistical evidence 
# that associated population means are significantly different

In [74]:
np.random.seed(2)
class_one=stats.poisson.rvs(loc=18,mu=33,size=60)
class_age=stats.poisson.rvs(loc=18,mu=30,size=60)
class_one.mean()

50.8

In [76]:
_,pvalue=stats.ttest_ind(class_age,class_one)

In [77]:
pvalue

0.0032637397549269156

In [78]:
if pvalue<0.05:
    print('reject the null hypo')
else:
    print('failed to reject the null hypo')

reject the null hypo


In [85]:
weight_one=np.linspace(10,100,15).round(0)
weight_second=weight_one+stats.norm.rvs(scale=5,loc=-1.25,size=15)

In [91]:
weight_one

array([ 10.,  16.,  23.,  29.,  36.,  42.,  49.,  55.,  61.,  68.,  74.,
        81.,  87.,  94., 100.])

In [95]:
df=pd.DataFrame({'weight_one':np.array(weight_one),'weight_two':np.array(weight_second),
              'weight_change':np.array(weight_second)-np.array(weight_one)})

<IPython.core.display.Javascript object>

In [96]:
df.head(3)

weight_one  weight_two  weight_change
0        10.0    9.052312      -0.947688
1        16.0    8.057056      -7.942944
2        23.0   27.413730       4.413730

In [103]:
_,pvalue1=stats.ttest_rel(weight_one,weight_second)

In [104]:
pvalue1

0.3530554320708219

In [105]:
if pvalue<0.05:
    print('reject the null hypo')
else:
    print('failed to reject the null hypo')

failed to reject the null hypo
